# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 160, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_management = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_management.setObjectName("button_management")
        self.verticalLayout.addWidget(self.button_management)
        self.button_items_to_be_tested = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_items_to_be_tested.setObjectName("button_items_to_be_tested")
        self.verticalLayout.addWidget(self.button_items_to_be_tested)
        self.button_list_of_test_means = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_list_of_test_means.setObjectName("button_list_of_test_means")
        self.verticalLayout.addWidget(self.button_list_of_test_means)
        self.button_list_of_configuration = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_list_of_configuration.setObjectName("button_list_of_configuration")
        self.verticalLayout.addWidget(self.button_list_of_configuration)
        self.button_test_execution = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_test_execution.setObjectName("button_test_execution")
        self.verticalLayout.addWidget(self.button_test_execution)
        self.button_exploitation_of_tests = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_exploitation_of_tests.setObjectName("button_exploitation_of_tests")
        self.verticalLayout.addWidget(self.button_exploitation_of_tests)
        self.button_user_query = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_user_query.setObjectName("button_user_query")
        self.verticalLayout.addWidget(self.button_user_query)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.button_exit.setGeometry(QtCore.QRect(480, 340, 75, 23))
        self.button_exit.setObjectName("button_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_management.setText(_translate("MainWindow", "Management"))
        self.button_items_to_be_tested.setText(_translate("MainWindow", "Items to be tested"))
        self.button_list_of_test_means.setText(_translate("MainWindow", "List of test means"))
        self.button_list_of_configuration.setText(_translate("MainWindow", "List of configuration"))
        self.button_test_execution.setText(_translate("MainWindow", "Test execution"))
        self.button_exploitation_of_tests.setText(_translate("MainWindow", "Exploitation of tests"))
        self.button_user_query.setText(_translate("MainWindow", "User query"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.button_exit.setText(_translate("MainWindow", "Exit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
